In [3]:
from sklearn import datasets
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
iris = datasets.load_iris()
# print(iris)
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target)
model = KMeans(n_clusters=3)
model.fit(X_train, y_train)
# model.score
print('K-Mean: ', metrics.accuracy_score(y_test, model.predict(X_test)))
#-------Expectation and Maximization----------
from sklearn.mixture import GaussianMixture
model2 = GaussianMixture(n_components=3)
model2.fit(X_train, y_train)
# model2.score
print('EM Algorithm: ', metrics.accuracy_score(y_test, model2.predict(X_test)))

K-Mean:  0.5263157894736842
EM Algorithm:  0.4473684210526316


## Or 

In [3]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.datasets import load_iris

iris = load_iris()

X = pd.DataFrame(iris.data)
y = iris.target

kmeans = KMeans(n_clusters=3).fit(X)
ypred = kmeans.predict(X)

print(classification_report(y, ypred, target_names=iris.target_names))
print("Confusion Matrix: \n", confusion_matrix(y, ypred))

print()
gmm = GaussianMixture(n_components = 3).fit(X)
y_cluster_gmm = gmm.predict(X)
print(classification_report(y, y_cluster_gmm, target_names = iris.target_names))
print("Confusion Matrix: \n", confusion_matrix(y, y_cluster_gmm))

# plt.figure(figsize=(14, 7))
# colormap = np.array(['Red', 'Lime', 'Black'])
# plt.subplot(1, 2, 1)
# plt.title('KMeans clustering')
# plt.scatter(X[2], X[3], c=colormap[ypred])
# plt.subplot(1, 2, 2)
# plt.title('GMM')
# plt.scatter(X[2], X[3], c=colormap[y_cluster_gmm])

              precision    recall  f1-score   support

      setosa       0.00      0.00      0.00        50
  versicolor       0.00      0.00      0.00        50
   virginica       0.95      0.72      0.82        50

    accuracy                           0.24       150
   macro avg       0.32      0.24      0.27       150
weighted avg       0.32      0.24      0.27       150

Confusion Matrix: 
 [[ 0 50  0]
 [48  0  2]
 [14  0 36]]

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        50
  versicolor       1.00      0.90      0.95        50
   virginica       0.91      1.00      0.95        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150

Confusion Matrix: 
 [[50  0  0]
 [ 0 45  5]
 [ 0  0 50]]
